### ISSUE TITLE
Can I add keycloke event logs and Admin logs to the table?

### ISSUE THREAD

**Issue by ghost** [theapsgroup/steampipe-plugin-keycloak#28]
Features developed so far are very well used. Can I also add event and admin logging capabilities?

**Comment by graza-io** [comment]
Should be possible to add as I can see it in the API docs, albeit may need to ensure it's included in the SDK.
[Realm Admin-Events](https://www.keycloak.org/docs-api/21.0.1/rest-api/index.html#_realms_admin_resource)

**Comment by graza-io** [comment]
Apologies for the delay - I've setup a branch for this issue and made an initial additional table `keycloak_event` - if you're comfortable building from source, feel free to test drive it :)

**Comment by graza-io** [comment]
@jinseokyeo - were you able to test this by building from source and if so, did you get your expected results?

**Comment by ghost** [comment]
@graza-io I'm sorry for the late reply. The desired results are extracted. Thank you.

**Comment by ghost** [comment]
Hello, I found a bug while checking the event log function, so I'm sharing it with you.

failed to populate column 'time': rpc error: code = Internal desc = transform convertTimestamp failed with panic interface conversion: interface {} is int64, not *int64 (SQLSTATE HV000

**Comment by graza-io** [comment]
Thanks, there's a fix on the `main` branch, will release with next update.
